with TOTAL_INV_AMNT AS (
SELECT SUM(INVOICE_AMOUNT) as TOTAL_INVOICE_AMOUNT,1 AS JOIN_FLAG FROM SF_POC.SF_MASKED_STAGE.NORMALISED_VENDOR_DATA_STAGE)

select Raw_ERP_Vendor_Name
,SPEND
,ROUND((SUM (SPEND) OVER  (ORDER BY SPEND DESC)/TOTAL_INVOICE_AMOUNT) * 100,2) AS CUM_PER
from (
SELECT Raw_ERP_Vendor_Name
,SUM(INVOICE_AMOUNT) as SPEND
from SF_POC.SF_MASKED_STAGE.NORMALISED_VENDOR_DATA_STAGE
group by 1
),TOTAL_INV_AMNT
WHERE 1 = TOTAL_INV_AMNT.JOIN_FLAG
ORDER BY SPEND DESC